### ISSUE TITLE
get_Item

### ISSUE THREAD

**Issue by fpedroso8** [dikirilov/dashboard_zabbix#1]
How do I get the value of an item ? appears only 3% 
thanks

**Comment by dikirilov** [comment]
There's gem 'Zabby' which perform such tasks.
Some examples and documentation you can find here: 
https://github.com/Pragmatic-Source/zabby

With item I use syntax:
Zabby::Item.get "filter" => {"itemid" => "44016"} }
If you don't know paricular id, you can use some filter options.

**Comment by fpedroso8** [comment]
Thank you, but when I do that it keeps bringing me the number 3% that you put ... could tell me what might be causing this?

**Comment by dikirilov** [comment]
Could you tell me exactly, where is that number appeared, and where you write you own code?

**Comment by fpedroso8** [comment]
cpu6_req = serv.run { Zabby::Item.get "filter" => {"itemid" => "23057"} }
cpu6 = JSON.parse(cpu6_req.to_json)[0]["lastvalue"]
send_event( 'cpu6', {current: cpu6, status: cpu6stats, updatedAt: time, suffix: "%"  } )
I just changed the itemid the number as itemid what's in my database, the code remains the same as yours, but even changing the itemid he keeps taking the value of your itemid

**Comment by dikirilov** [comment]
How did you get you itemid? 
I can find such ids only using zabby shell. Throw it I connect to Zabbix API and try to get proper information. Probably you have wrong number of id. In cause of that the value of widget may not refresh. 
To figure it out, just try to output debug information, add to the end of job file this:
p cpu6
In console where you starting server you will see the value of cpu6 variable.

**Comment by fpedroso8** [comment]
thanks for the help, did a check and could run even thank you!
